spring.application.name=StudentManagement

# H2???
spring.datasource.url=jdbc:h2:~/test;MODE=MYSQL
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true

# SpringDoc??? (Swagger UI)
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

spring.datasource.schema=classpath:schema.sql
spring.datasource.initialization-mode=always


# MyBatis???
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:/mappers/*.xml

# Hibernate??? (H2 ?)
spring.jpa.hibernate.ddl-auto=update

# ??????????????
server.error.include-message=always
server.error.include-binding-errors=always

# JVM ?????? (Gradle)
org.gradle.jvmargs=-Xmx2048m

# ????????
logging.level.org.mybatis=DEBUG
logging.level.org.springframework.jdbc.datasource.DataSourceTransactionManager=DEBUG
